### ISSUE TITLE
运行server.php报错了

### ISSUE THREAD

**Issue by meahu** [zhenbianshu/websocket#1]
运行server.php报错了：
Parse error: syntax error, unexpected '[' in D:\www\chat2\server.php on line 19

**Comment by zhenbianshu** [comment]
请问你的PHP是什么版本的，可能不支持在声明类变量时赋值，也可能是不支持[]数组赋值。

**Comment by RicardoWxc** [comment]
运行时报错
client.html:36 WebSocket connection to 'ws://127.0.0.1:8000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
还有解析错误和楼上一样
C:\Users\ADMIN>php -qc: D:\wamp64\www\websocket\server.php
Parse error: syntax error, unexpected '[' in D:\wamp64\www\websocket\server.php
on line 19

**Comment by 18y** [comment]
Fatal error: Call to undefined function socket_create() in C:\lyadmin\phpStudy\WWW\websocket-master\server.php on line 24

**Comment by zhenbianshu** [comment]
重新编译php，带上sockets扩展就行了。

**Comment by xiejilin** [comment]
“系统消息 : 出错了,请退出重试.”这个怎么解决啊？
