### ISSUE TITLE
如何区分用户连接

### ISSUE THREAD

**Issue by phpstudyone** [zhenbianshu/websocket#2]
假设有ABC三个用户登录，链接上了服务端。那么如何区分这三个不同的链接，因为我想实现 A发送一个消息 只推送给B的功能。

**Comment by zhenbianshu** [comment]
你可以使用 `socket_getpeername($client, $ip, $port)` 函数，将ip和端口写入$ip和 $port中。

**Comment by phpstudyone** [comment]
不是很懂，我获取到客户的ip和端口有啥用。。。我要把a发送的消息转发给b，把c的消息转发给d。作为服务端来说，无法知道各客户的ip对应关系呀。而且感觉用ip来标志一个用户是否不准确？

**Comment by zhenbianshu** [comment]
你可以参考下我项目里的实现，我在握手成功后强制客户端发送一个用户名给服务端，服务端用这个用户名来分辨不同的客户端。

具体设计你可以看下我的博客：[网页实时聊天之PHP实现websocket](http://www.cnblogs.com/zhenbianshu/p/6111257.html)

**Comment by phpstudyone** [comment]
非常感谢：
那么类似于 C socket 的 PHP socket 自然也继承了这一点，它创建的 socket 也是类型于 int 值为 4 5 之类的资源类型。 我们可以使用` (int)` 或 `intval()` 函数把 socket 转换为一个唯一的ID，从而可以实现用一个 ’类索引数组‘ 来存储 socket 资源和对应的用户信息；

看到这里才懂了，每一个客户端链接进来，都能获取一个    `$client = socket_accept($sock);` 而这个`$client` 都不一样，可以强制转为`(int)` ,从而来标志客户机，
