### ISSUE TITLE
绑定127.0.0.1的端口后，127.0.0.1下的其他php都没用了，html还能访问

### ISSUE THREAD

**Issue by 582302894** [zhenbianshu/websocket#3]

**Comment by zhenbianshu** [comment]
首先弄清这个 websocket 是个什么角色： 类似nginx(apache)。

ip和端口 来唯一标识一个服务。
它监听 127.0.0.1 的 8080 端口，nginx 监听 127.0.0.1 的 80 端口。
它只处理 127.0.0.1:8080/xxx.php 的请求，  而 nginx 处理 127.0.0.1/xxx.php html 请求。

所以，html 是由nginx/apache 来处理的，不是由这个后台脚本。
