### ISSUE TITLE
Unable to run on Windows platform under PHP7.4.8

### ISSUE THREAD

**Issue by Ezharjan** [zhenbianshu/websocket#6]
Hi, your code `server.php` seems well done but it fails when I'm running it with the command below:
```bash
php server.php
```
<br>

The exact error is shown below:
```bash
PHP Fatal error:  Uncaught Error: Call to undefined function socket_create() in D:\Trashes\websocket-master\server.php:24      
```
detailed screenshot is shown below:

![图片](https://user-images.githubusercontent.com/60126466/105655590-473e4e80-5efb-11eb-8163-d863d6ba54f2.png)

![图片](https://user-images.githubusercontent.com/60126466/105655649-6806a400-5efb-11eb-99f4-faaddca438fc.png)

<br>

It seems that the server side has some problems on platform compatibility.
May you give me some advice on running it or any suggestions on developing WebSocket related server based on a Windows platform using PHP is warmly welcome!

**Comment by zhenbianshu** [comment]
抱歉，我已经太久没写过 PHP 代码了。。也不知道 PHP 新版本添加了什么特性，建议您可以先了解一下实现原理，再查询一下 PHP socket 相关的 API 实现 :)

**Comment by dreamncn** [comment]
Literally, you may need to enable the [socket extension](https://www.php.net/manual/en/sockets.installation.php).
